AddCSLuaFile("shared.lua")
include('shared.lua')
/*-----------------------------------------------
	*** Copyright (c) 2012-2019 by DrVrej, All rights reserved. ***
	No parts of this code or any of its contents may be reproduced, copied, modified or adapted,
	without the prior written consent of the author, unless otherwise indicated for stand-alone materials.
-----------------------------------------------*/
ENT.VJ_NPC_Class = {"CLASS_ZOMBIE"} -- NPCs with the same class with be allied to each other
ENT.NoWeapon_UseScaredBehavior = false
---------------------------------------------------------------------------------------------------------------------------------------------
function ENT:Security_CustomOnInitialize()
	self.SoundTbl_Idle = {"vj_hlr/hl1_npc/barney/whatisthat.wav","vj_hlr/hl1_npc/barney/somethingstinky.wav","vj_hlr/hl1_npc/barney/somethingdied.wav","vj_hlr/hl1_npc/barney/guyresponsible.wav","vj_hlr/hl1_npc/barney/coldone.wav","vj_hlr/hl1_npc/barney/ba_gethev.wav","vj_hlr/hl1_npc/barney/badfeeling.wav","vj_hlr/hl1_npc/barney/bigmess.wav","vj_hlr/hl1_npc/barney/bigplace.wav"}
	self.SoundTbl_IdleDialogue = {"vj_hlr/hl1_npc/barney/youeverseen.wav","vj_hlr/hl1_npc/barney/workingonstuff.wav","vj_hlr/hl1_npc/barney/whatsgoingon.wav","vj_hlr/hl1_npc/barney/thinking.wav","vj_hlr/hl1_npc/barney/survive.wav","vj_hlr/hl1_npc/barney/stench.wav","vj_hlr/hl1_npc/barney/somethingmoves.wav","vj_hlr/hl1_npc/barney/of1a5_ba01.wav","vj_hlr/hl1_npc/barney/nodrill.wav","vj_hlr/hl1_npc/barney/missingleg.wav","vj_hlr/hl1_npc/barney/luckwillturn.wav","vj_hlr/hl1_npc/barney/gladof38.wav","vj_hlr/hl1_npc/barney/gettingcloser.wav","vj_hlr/hl1_npc/barney/crewdied.wav","vj_hlr/hl1_npc/barney/ba_idle0.wav","vj_hlr/hl1_npc/barney/badarea.wav","vj_hlr/hl1_npc/barney/beertopside.wav"}
	self.SoundTbl_IdleDialogueAnswer = {"vj_hlr/hl1_npc/barney/yup.wav","vj_hlr/hl1_npc/barney/youtalkmuch.wav","vj_hlr/hl1_npc/barney/yougotit.wav","vj_hlr/hl1_npc/barney/youbet.wav","vj_hlr/hl1_npc/barney/yessir.wav","vj_hlr/hl1_npc/barney/soundsright.wav","vj_hlr/hl1_npc/barney/noway.wav","vj_hlr/hl1_npc/barney/nope.wav","vj_hlr/hl1_npc/barney/nosir.wav","vj_hlr/hl1_npc/barney/notelling.wav","vj_hlr/hl1_npc/barney/maybe.wav","vj_hlr/hl1_npc/barney/justdontknow.wav","vj_hlr/hl1_npc/barney/ireckon.wav","vj_hlr/hl1_npc/barney/iguess.wav","vj_hlr/hl1_npc/barney/icanhear.wav","vj_hlr/hl1_npc/barney/guyresponsible.wav","vj_hlr/hl1_npc/barney/dontreckon.wav","vj_hlr/hl1_npc/barney/dontguess.wav","vj_hlr/hl1_npc/barney/dontfigure.wav","vj_hlr/hl1_npc/barney/dontbuyit.wav","vj_hlr/hl1_npc/barney/dontbet.wav","vj_hlr/hl1_npc/barney/dontaskme.wav","vj_hlr/hl1_npc/barney/cantfigure.wav","vj_hlr/hl1_npc/barney/bequiet.wav","vj_hlr/hl1_npc/barney/ba_stare0.wav","vj_hlr/hl1_npc/barney/alreadyasked.wav"}
	self.SoundTbl_CombatIdle = {"vj_hlr/hl1_npc/barney/whatgood.wav","vj_hlr/hl1_npc/barney/targetpractice.wav","vj_hlr/hl1_npc/barney/easily.wav","vj_hlr/hl1_npc/barney/getanyworse.wav"}
	self.SoundTbl_FollowPlayer = {"vj_hlr/hl1_npc/barney/yougotit.wav","vj_hlr/hl1_npc/barney/wayout.wav","vj_hlr/hl1_npc/barney/teamup1.wav","vj_hlr/hl1_npc/barney/teamup2.wav","vj_hlr/hl1_npc/barney/rightway.wav","vj_hlr/hl1_npc/barney/letsgo.wav","vj_hlr/hl1_npc/barney/letsmoveit.wav","vj_hlr/hl1_npc/barney/imwithyou.wav","vj_hlr/hl1_npc/barney/gladtolendhand.wav","vj_hlr/hl1_npc/barney/dobettertogether.wav","vj_hlr/hl1_npc/barney/c1a2_ba_goforit.wav","vj_hlr/hl1_npc/barney/ba_ok1.wav","vj_hlr/hl1_npc/barney/ba_ok2.wav","vj_hlr/hl1_npc/barney/ba_ok3.wav","vj_hlr/hl1_npc/barney/ba_idle1.wav","vj_hlr/hl1_npc/barney/ba_ht06_11.wav"}
	self.SoundTbl_UnFollowPlayer = {"vj_hlr/hl1_npc/barney/waitin.wav","vj_hlr/hl1_npc/barney/stop2.wav","vj_hlr/hl1_npc/barney/standguard.wav","vj_hlr/hl1_npc/barney/slowingyoudown.wav","vj_hlr/hl1_npc/barney/seeya.wav","vj_hlr/hl1_npc/barney/iwaithere.wav","vj_hlr/hl1_npc/barney/illwait.wav","vj_hlr/hl1_npc/barney/helpothers.wav","vj_hlr/hl1_npc/barney/ba_wait1.wav","vj_hlr/hl1_npc/barney/ba_wait2.wav","vj_hlr/hl1_npc/barney/ba_wait3.wav","vj_hlr/hl1_npc/barney/ba_wait4.wav","vj_hlr/hl1_npc/barney/ba_security2_pass.wav","vj_hlr/hl1_npc/barney/aintgoin.wav","vj_hlr/hl1_npc/barney/ba_becareful1.wav"}
	self.SoundTbl_OnPlayerSight = {"vj_hlr/hl1_npc/barney/mrfreeman.wav","vj_hlr/hl1_npc/barney/howyoudoing.wav","vj_hlr/hl1_npc/barney/howdy.wav","vj_hlr/hl1_npc/barney/heybuddy.wav","vj_hlr/hl1_npc/barney/heyfella.wav","vj_hlr/hl1_npc/barney/hellonicesuit.wav","vj_hlr/hl1_npc/barney/ba_stare1.wav","vj_hlr/hl1_npc/barney/ba_later.wav","vj_hlr/hl1_npc/barney/ba_idle4.wav","vj_hlr/hl1_npc/barney/ba_idle3.wav","vj_hlr/hl1_npc/barney/ba_ok4.wav","vj_hlr/hl1_npc/barney/ba_ok5.wav","vj_hlr/hl1_npc/barney/ba_ht06_03.wav","vj_hlr/hl1_npc/barney/ba_ht06_03_alt.wav","vj_hlr/hl1_npc/barney/ba_hello0.wav","vj_hlr/hl1_npc/barney/ba_hello1.wav","vj_hlr/hl1_npc/barney/ba_hello2.wav","vj_hlr/hl1_npc/barney/ba_hello3.wav","vj_hlr/hl1_npc/barney/ba_hello4.wav","vj_hlr/hl1_npc/barney/ba_hello5.wav","vj_hlr/hl1_npc/barney/armedforces.wav"}
	self.SoundTbl_Investigate = {"vj_hlr/hl1_npc/barney/youhearthat.wav","vj_hlr/hl1_npc/barney/soundsbad.wav","vj_hlr/hl1_npc/barney/icanhear.wav","vj_hlr/hl1_npc/barney/hearsomething2.wav","vj_hlr/hl1_npc/barney/hearsomething.wav","vj_hlr/hl1_npc/barney/ambush.wav","vj_hlr/hl1_npc/barney/ba_generic0.wav"}
	self.SoundTbl_Alert = {"vj_hlr/hl1_npc/barney/ba_openfire.wav","vj_hlr/hl1_npc/barney/ba_attack1.wav","vj_hlr/hl1_npc/barney/aimforhead.wav"}
	self.SoundTbl_CallForHelp = {"vj_hlr/hl1_npc/barney/ba_needhelp0.wav","vj_hlr/hl1_npc/barney/ba_needhelp1.wav"}
	self.SoundTbl_BecomeEnemyToPlayer = {"vj_hlr/hl1_npc/barney/ba_uwish.wav","vj_hlr/hl1_npc/barney/ba_tomb.wav","vj_hlr/hl1_npc/barney/ba_somuch.wav","vj_hlr/hl1_npc/barney/ba_mad3.wav","vj_hlr/hl1_npc/barney/ba_iwish.wav","vj_hlr/hl1_npc/barney/ba_endline.wav","vj_hlr/hl1_npc/barney/aintscared.wav"}
	self.SoundTbl_Suppressing = {"vj_hlr/hl1_npc/barney/c1a4_ba_octo2.wav","vj_hlr/hl1_npc/barney/c1a4_ba_octo4.wav","vj_hlr/hl1_npc/barney/c1a4_ba_octo3.wav","vj_hlr/hl1_npc/barney/ba_generic1.wav","vj_hlr/hl1_npc/barney/ba_bring.wav","vj_hlr/hl1_npc/barney/ba_attacking1.wav"}
	self.SoundTbl_OnGrenadeSight = {"vj_hlr/hl1_npc/barney/standback.wav","vj_hlr/hl1_npc/barney/ba_heeey.wav"}
	self.SoundTbl_OnKilledEnemy = {"vj_hlr/hl1_npc/barney/soundsbad.wav","vj_hlr/hl1_npc/barney/ba_seethat.wav","vj_hlr/hl1_npc/barney/ba_kill0.wav","vj_hlr/hl1_npc/barney/ba_gotone.wav","vj_hlr/hl1_npc/barney/ba_firepl.wav","vj_hlr/hl1_npc/barney/ba_buttugly.wav","vj_hlr/hl1_npc/barney/ba_another.wav","vj_hlr/hl1_npc/barney/ba_close.wav"}
	self.SoundTbl_AllyDeath = {"vj_hlr/hl1_npc/barney/die.wav"}
	self.SoundTbl_Pain = {"vj_hlr/hl1_npc/barney/imhit.wav","vj_hlr/hl1_npc/barney/hitbad.wav","vj_hlr/hl1_npc/barney/c1a2_ba_4zomb.wav","vj_hlr/hl1_npc/barney/ba_pain1.wav","vj_hlr/hl1_npc/barney/ba_pain2.wav","vj_hlr/hl1_npc/barney/ba_pain3.wav"}
	self.SoundTbl_DamageByPlayer = {"vj_hlr/hl1_npc/barney/donthurtem.wav","vj_hlr/hl1_npc/barney/ba_whoathere.wav","vj_hlr/hl1_npc/barney/ba_whatyou.wav","vj_hlr/hl1_npc/barney/ba_watchit.wav","vj_hlr/hl1_npc/barney/ba_shot1.wav","vj_hlr/hl1_npc/barney/ba_shot2.wav","vj_hlr/hl1_npc/barney/ba_shot3.wav","vj_hlr/hl1_npc/barney/ba_shot4.wav","vj_hlr/hl1_npc/barney/ba_shot5.wav","vj_hlr/hl1_npc/barney/ba_shot6.wav","vj_hlr/hl1_npc/barney/ba_shot7.wav","vj_hlr/hl1_npc/barney/ba_stepoff.wav","vj_hlr/hl1_npc/barney/ba_pissme.wav","vj_hlr/hl1_npc/barney/ba_mad1.wav","vj_hlr/hl1_npc/barney/ba_mad0.wav","vj_hlr/hl1_npc/barney/ba_friends.wav","vj_hlr/hl1_npc/barney/ba_dotoyou.wav","vj_hlr/hl1_npc/barney/ba_dontmake.wav","vj_hlr/hl1_npc/barney/ba_crazy.wav"}
	self.SoundTbl_Death = {"vj_hlr/hl1_npc/barney/ba_ht06_02_alt.wav","vj_hlr/hl1_npc/barney/ba_ht06_02.wav","vj_hlr/hl1_npc/barney/ba_die1.wav","vj_hlr/hl1_npc/barney/ba_die2.wav","vj_hlr/hl1_npc/barney/ba_die3.wav"}

	self.AnimTbl_Death = {ACT_DIEBACKWARD,ACT_DIEFORWARD,ACT_DIE_GUTSHOT,ACT_DIE_HEADSHOT,ACT_DIESIMPLE} -- Death Animations
	self:Give("weapon_vj_hlrze_spas12")
	
	self:SetSkin(1)
end
---------------------------------------------------------------------------------------------------------------------------------------------
VJ.AddNPC("Barney Bruiser","npc_vj_bhorde_hlze_barney_bruiser", "Zombies")
/*-----------------------------------------------
	*** Copyright (c) 2012-2019 by DrVrej, All rights reserved. ***
	No parts of this code or any of its contents may be reproduced, copied, modified or adapted,
	without the prior written consent of the author, unless otherwise indicated for stand-alone materials.
-----------------------------------------------*/